name: Build and Push Image

on:
  push:
    branches: [ main ]

jobs:
  build:
    permissions:
      contents: read
      packages: write
    uses: ohmyplatform/actions/.github/workflows/build_and_push.yml@v1
    with:
      dockerfile: ./src/${{ values.name }}.Api/Dockerfile
      docker_context: src

  updateArgoCDApp:
    needs: build
    uses: ohmyplatform/actions/.github/workflows/update_argocd_apps.yml@v1
    permissions:
      contents: read
      id-token: write
      checks: write
      statuses: write
    with:
      value: {% raw %}ghcr.io/${{ github.repository }}:${{ github.sha }}{% endraw %}
    secrets:
      ARGOCD_APPS_DEPLOY_KEY: {% raw %}${{ secrets.ARGOCD_APPS_DEPLOY_KEY }}{% endraw %}