apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | lower | dump }}
  annotations:
    github.com/project-slug: ${{__GITHUB_ORG__}}/${{ values.name | lower }}
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: group:platform
  lifecycle: experimental
