apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{values.name}}
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    notifications.argoproj.io/subscribe.on-sync-status-unknown.github: ""
    notifications.argoproj.io/subscribe.on-sync-succeeded.github: ""
    notifications.argoproj.io/subscribe.on-sync-failed.github: ""
spec:
  destination:
    namespace: ${{values.name}}
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    repoURL: git@github.com:qwiklabs-gcp-04-f602ff6239fc/argocd-apps.git
    targetRevision: main
    path: configuration/${{values.name}}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
