apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ${{values.name}}
  name: ${{values.name}}
  namespace: ${{values.name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${{values.name}}
  template:
    metadata:
      labels:
        app: ${{values.name}}
    spec:
      containers:
      - image: ghcr.io/qwiklabs-gcp-04-f602ff6239fc/${{values.name}}
        name: ${{values.name}}
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP