apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${{values.name}}
  namespace: ${{values.name}}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: "nginx"
  tls:
    - hosts:
      - ${{values.name}}.${{__GITHUB_ORG__}}.ohmyplatform.com
      secretName: ${{values.name}}-tls
  rules:
    - host: ${{values.name}}.${{__GITHUB_ORG__}}.ohmyplatform.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ${{values.name}}
                port:
                  name: http